---
- name: Build docker image Worker
  docker_image:
    build:
      path: "{{ worker_dir }}"
    name: celery_worker

- name: Get KLEE image from Docker Hub (this may take a while...)
  docker_image:
    name: klee/klee
    tag: latest
