---
- name: Start docker Worker
  docker_container:
    name: worker_1
    image: celery_worker
    command: "/bin/bash {{ runner_path }} celery -A worker.worker worker"
    restart_policy: always
    volumes: 
    # allow this container to start other Docker containers:
    - /var/run/docker.sock:/var/run/docker.sock
    - /tmp/:/tmp/
    networks: 
      - name: "{{ container_network }}"
