---
# version: 2
# jobs:
#   build:
#     # machine: 
#     #   image: ubuntu-1604:201903-01
#     docker:
#       - image: circleci/python:3.7.3
#     steps:
#       - checkout  
#       # - run: sudo apt-get install software-properties-common
#       # - run: sudo apt-get update -qq
#       # - run: pyenv install 3.7.2
#       # - run: pyenv global 3.7.2
#       # - run: sudo apt install python3-pip
#       # - run: sudo pip install ansible
#       # - run: sudo ln -s /home/circleci/project/ /titb
#       # - run: sudo ansible-galaxy install --force --role-file=requirements.yml
#       # - run: cd /titb/
#       # - run: sudo ansible-playbook -i localhost, --syntax-check ./provisioning/vagrant.yml
#       # - run: sudo ansible-playbook -i localhost, --connection=local -vvv -e ci=yes ./provisioning/vagrant.yml
#       # - run: . run_tests.sh
#       - run: sudo apt-get install software-properties-common
#       # - run: sudo apt-add-repository ppa:ansible/ansible -y
#       - run: sudo apt-get update -qq
#       - run: sudo pip install ansible
#       - run: sudo pip install docker-py
#       - run: sudo ln -s /home/circleci/project/ /titb
#       - run: ansible-galaxy install --force --role-file=requirements.yml
#       - run: cd /titb/
#       - run: ansible-playbook -i localhost, --syntax-check provisioning/vagrant.yml
#       - run: ansible-playbook -i localhost, --connection=local -e ci=yes provisioning/vagrant.yml
#       - run: ./run_tests.sh

version: 2
jobs:
  build:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      - checkout  
      - run: sudo apt-get install software-properties-common
      - run: sudo apt-get update -qq
      # - run: pyenv install 3.7.2
      # - run: pyenv global 3.7.2
      # can do:
      - run: pyenv global 3.7.0  # can also update later if needed
      - run: sudo apt install python3-pip
      - run: sudo pip install ansible
      - run: sudo ln -s /home/circleci/project/ /titb
      - run: sudo ansible-galaxy install --force --role-file=requirements.yml
      - run: cd /titb/
      - run: sudo ansible-playbook -i localhost, --syntax-check ./provisioning/vagrant.yml
      # - run: pyenv global 2.7.12
      - run: sudo ansible-playbook -i localhost, --connection=local -vvv -e ci=yes ./provisioning/vagrant.yml
      - run: pyenv global 3.7.2
      - run: . run_tests.sh
