---
version: 2
jobs:
  build:
    machine: 
      image: ubuntu-1604:201903-01
    steps:
      # ---- Provisioning ----
      - checkout  
      - run: sudo apt-get update -qq
      - run: sudo apt-get install software-properties-common
      - run: sudo apt install python3-pip
      - run: sudo pip install ansible
      - run: sudo ln -s /home/circleci/project/ /titb
      - run: sudo ansible-galaxy install --force --role-file=requirements.yml
      - run: cd /titb/
      - run: sudo ansible-playbook -i localhost, --syntax-check ./provisioning/vagrant.yml
      - run: sudo ansible-playbook -i localhost, --connection=local -vvv -e ci=yes ./provisioning/vagrant.yml
      - run: sudo ansible-playbook -i localhost, --connection=local -vvv ./provisioning/e2e.yml
      # ---- Python related tests ----
      - run: sudo docker run --rm -it --network host -v /titb/:/titb/ e2e_test /bin/bash /titb/src/klee_web/tests/python_tests/flake8_test.sh
      - run: sudo docker run --rm -it --network host -v /var/run/docker.sock:/var/run/docker.sock -v /etc/profile.d/:/etc/profile.d/ -v /tmp/:/tmp/ -v /titb/:/titb/ e2e_test /bin/bash /titb/src/klee_web/tests/python_tests/unit_tests.sh
      - run: sudo docker run --rm -it --network host -v /titb/src/klee_web/tests/python_tests/:/titb/src/klee_web/tests/python_tests/ e2e_test /bin/bash /titb/src/klee_web/tests/python_tests/webserver_test.sh
      # ---- JavaScript end-to-end tests ----
      - run: sudo docker run --rm -it --network host -v /titb/src/klee_web/tests/js_tests/test_files/:/titb/src/klee_web/tests/js_tests/test_files/ e2e_test_js
