---
# - name: Remove existing geoip directory
#   file:
#     path: "{{ application_dir }}/geoip/"
#     state: absent

- name: Start docker klee-web
  docker_container:
    name: django_app
    image: klee_web
    restart_policy: always
    networks: 
      - name: "{{ container_network }}"
    volumes:
      - /tmp:/tmp
      # source code folders:
      - "{{ application_dir }}:{{ application_dir }}"
      - "{{ code_dir }}/worker:{{ code_dir }}/worker"
      # files for secrets and environmental variables:
      - "{{ admin_ps_dir }}/admin_psw.sh:{{ admin_ps_dir }}/admin_psw.sh"
      - "{{ klee_web_env }}:{{ klee_web_env }}"
    recreate: yes
