---

# Install frontend dependencies

- name: "Add official NodeJS repo 6.x"
  shell: curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
  tags: nodejs

- name: "Install node.js"
  apt: name=nodejs update_cache=yes
  tags: nodejs

- name: "Update npm"
  npm: name=npm global=yes state=latest

- name: "Install grunt-cli"
  npm: name=grunt-cli global=yes

- name: "Install grunt"
  npm: name=grunt path="{{ src_dir }}"

- name: "Install grunt module sass"
  npm: name=grunt-contrib-sass path="{{ src_dir }}"

- name: "Install grunt module watch"
  npm: name=grunt-contrib-watch path="{{ src_dir }}"

- name: "Install grunt module copy"
  npm: name=grunt-contrib-copy path="{{ src_dir }}"

- name: "Install grunt module concat"
  npm: name=grunt-contrib-concat path="{{ src_dir }}"

- name: "Install grunt module uglify"
  npm: name=grunt-contrib-uglify path="{{ src_dir }}"

- name: "Install bower"
  npm: name=bower global=yes

- name: "Install node dependencies"
  npm: path={{ src_dir }}
  become: yes
  become_user: klide

- name: "Add brightbox ruby"
  apt_repository: repo='ppa:brightbox/ruby-ng'
  tags: setup

- name: "Install ruby"
  apt: name={{ item }} update_cache=yes state=latest
  with_items:
    - ruby2.3
    - ruby2.3-dev

- name: "Set ruby2.3 to be the default one"
  shell: update-alternatives --set ruby /usr/bin/ruby2.3

- name: Install SASS
  command: gem install sass
