---

# Install python dev
- apt: name=python-dev update_cache=yes state=present

- name: Install python-pip package
  apt: name=python-pip update_cache=yes state=present

# Install virtualenv
- command: pip install virtualenv

- file: name=/titb/src/klee_web/geoip state=directory

- file: name=/titb/src/geoip state=directory

- get_url: url=https://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz dest=/titb/src/geoip/

- get_url: url=https://geolite.maxmind.com/download/geoip/database/GeoLite2-Country.mmdb.gz dest=/titb/src/geoip/

- shell: gunzip -f /titb/src/geoip/GeoLite2-City.mmdb.gz

- shell: gunzip -f /titb/src/geoip/GeoLite2-Country.mmdb.gz

- name: Create web user
  user: name=klee_web shell=/bin/bash

- name: Create folder for web files
  file: path={{ web_working_dir }} owner=klee_web group=klee_web state=directory

- name: Create folder for web log files
  file: path={{ web_log_dir }} owner=klee_web group=klee_web state=directory

# Install supervisor
- apt: name=supervisor update_cache=yes state=present

- name: Start supervisor service
  service: name=supervisor state=started
