---
- name: Start docker Redis
  docker_container:
    name: kleeweb-redis
    image: redis:3.2
    restart_policy: always
    networks: 
      - name: "{{ container_network }}"
    ports:
      - "6379:6379"
    recreate: yes
