---
- hosts: all
  remote_user: vagrant
  become: yes
  vars:
    pip_install_packages:
      - name: docker
  vars_files:
    - vars/secrets.yml
    - vars/worker-prod.yml
    - vars/common.yml
  roles:
    - init
    # Need to install Python2 as well for Docker dependencies.
    - role: geerlingguy.pip
      pip_package: python-pip
    - role: geerlingguy.pip
      pip_package: python3-pip
      pip_executable: pip3
    - role: geerlingguy.docker

- hosts: master
  remote_user: vagrant
  become: yes
  vars_files:
    - vars/secrets.yml
    - vars/master-prod.yml
    - vars/common.yml
  roles:
    - common
    - redis
    - db
    - web

- hosts: worker
  remote_user: vagrant
  become: yes
  vars_files:
    - vars/secrets.yml
    - vars/worker-prod.yml
    - vars/common.yml
  roles:
    - common
    - worker

- hosts: testing
  remote_user: vagrant
  become: yes
  vars_files:
    - vars/secrets.yml
    - vars/worker-prod.yml
    - vars/common.yml
  roles:
    - common
    - e2e-tests
