---
- name: Build Python e2e_test image
  docker_image:
    build:
      path: "{{ application_dir }}"
      dockerfile: ./tests/python_tests/Dockerfile
    name: e2e_test

- name: Build JavaScript e2e_test image
  docker_image:
    build:
      path: "{{ application_dir }}/tests/js_tests"
    name: e2e_test_js

- name: Add cronjob for automated tests daily at 2pm
  cron:
    name: "Test Klee Web"
    minute: "5"
    hour: "22"
    job: "/src/python_runner.sh /usr/bin/python3 /titb/src/klee_web/tests/automated_e2e_tests.py"
    user: "{{ 'dg3718' if (not development) else 'vagrant' }}"
  when: not ci  # maybe: ci is not defined
