---
- name: Build Python e2e_test image
  docker_image:
    build:
      path: "{{ application_dir }}"
      dockerfile: ./tests/python_tests/Dockerfile
    name: e2e_test

- name: Build JavaScript e2e_test image
  docker_image:
    build:
      path: "{{ application_dir }}/tests/js_tests"
    name: e2e_test_js
